---
title: "Homework 3"
author: "Aditya A Satpute"
date: "2023-11-20"
output: html_document
---


```{r Traditional}

# ABC EXPERIMENT

# PARAMETERS
library(data.table)
set.seed(123)

pA <- 0.09; pB <- 0.15; pC <- 0.10

traffic <- 30000

rounds <- 100

ABC <- data.table()

# SIMULATION

for (round in 1:rounds) {
  
  n_A=round(traffic/3,0)
  
  n_B=round(traffic/3,0)
  
  n_C=round(traffic/3,0)
  
  conv_A = sum(rbinom(n_A, 1, pA))
  
  conv_B = sum(rbinom(n_A, 1, pB))
  
  conv_C = sum(rbinom(n_A, 1, pC))
  
  conv_total = sum(conv_A,conv_B,conv_C)
  
  cr_A = round(conv_A/(n_A),2)
  
  cr_B = round(conv_B/(n_A),2)
  
  cr_C = round(conv_C/(n_A),2)
  
  cr_total=round(conv_total/(n_A+n_B+n_C),2)
  
  ABC <- rbind(ABC, data.table(round, traffic, n_A, n_B, n_C, conv_total, conv_A, conv_B, conv_C, cr_total, cr_A, cr_B, cr_C))
  
}

# OUTPUT RESULTS

cat("\nTotal Results for", rounds, "Rounds\n",
    
    "Visitors_Total =", sum(ABC$traffic), "\n",
    
    "Visitors_A =", sum(ABC$n_A), "\n",
    
    "Visitors_B =", sum(ABC$n_B), "\n",
    
    "Visitors_C =", sum(ABC$n_C), "\n",
    
    "Total Conversions =", sum(ABC$conv_total), "\n",
    
    "Conversions for A =", sum(ABC$conv_A), "\n",
    
    "Conversions for B =", sum(ABC$conv_B), "\n",
    
    "Conversions for C =", sum(ABC$conv_C), "\n",
    
    "CR Total=", sum(ABC$conv_total)/sum(ABC$traffic)*100,"%", "\n",
    
    "CR_A =", sum(ABC$conv_A)/sum(ABC$n_A), "\n",
    
    "CR_B =", sum(ABC$conv_B)/sum(ABC$n_B), "\n",
    
    "CR_C =", sum(ABC$conv_C)/sum(ABC$n_C), "\n")

head(ABC)

```


```{r Greedy}

########################################################################################
#################### Greedy algorithm ########################################

# PARAMETERS

set.seed(123)

pA <- 0.09; pB <- 0.15; pC <- 0.10

traffic <- 30000

rounds <- 100

ABC_1 <- data.table()

conv_Tot <- 0

traffic_tot <- 0

net_conv <- 0

# SIMULATION

for (round in 1:rounds) {
  
  if(round <=25){
    
    n_A=round(traffic/3,0)
    
    n_B=round(traffic/3,0)
    
    n_C=round(traffic/3,0)
    
  }
  else {
    
    n_A = ifelse(cr_A > cr_B && cr_A > cr_C, traffic, 0)
    n_B = ifelse(cr_B > cr_A && cr_B > cr_C, traffic, 0)
    n_C = ifelse(cr_C > cr_A && cr_C > cr_B, traffic, 0)
    
    }
  
  
  conv_A = ifelse(n_A == 0, 0, sum(rbinom(n_A, 1, pA))) 
  
  conv_B = ifelse(n_B == 0, 0, sum(rbinom(n_B, 1, pB))) 
  
  conv_C = ifelse(n_C == 0, 0, sum(rbinom(n_C, 1, pC))) 
  
  conv_total = sum(conv_A,conv_B,conv_C)
  
  cr_A = ifelse(n_A == 0, 0, round(conv_A/(n_A),2))
  
  cr_B = ifelse(n_B == 0, 0, round(conv_B/(n_B),2))
  
  cr_C = ifelse(n_C == 0, 0, round(conv_C/(n_C),2))
  
  cr_total=round(conv_total/(n_A+n_B+n_C),2)
  
  conv_Tot <- conv_Tot + conv_total
  
  traffic_tot <- traffic_tot + n_A + n_B + n_C
  
  net_conv <- conv_Tot/traffic_tot
  
  ABC_1 <- rbind(ABC_1, data.table(round, traffic, n_A, n_B, n_C, conv_total, conv_A, conv_B, conv_C, cr_total, cr_A, cr_B, cr_C, conv_Tot, traffic_tot, net_conv))
  rate <- c(cr_A, cr_B, cr_C)
  
}

# OUTPUT RESULTS

cat("\nTotal Results for", rounds, "Rounds\n",
    
    "Visitors_Total =", sum(ABC_1$traffic), "\n",
    
    "Visitors_A =", sum(ABC_1$n_A), "\n",
    
    "Visitors_B =", sum(ABC_1$n_B), "\n",
    
    "Visitors_C =", sum(ABC_1$n_C), "\n",
    
    "Total Conversions =", sum(ABC_1$conv_total), "\n",
    
    "Conversions for A =", sum(ABC_1$conv_A), "\n",
    
    "Conversions for B =", sum(ABC_1$conv_B), "\n",
    
    "Conversions for C =", sum(ABC_1$conv_C), "\n",
    
    "CR Total=", sum(ABC_1$conv_total)/sum(ABC_1$traffic)*100,"%", "\n",
    
    "CR_A =", sum(ABC_1$conv_A)/sum(ABC_1$n_A), "\n",
    
    "CR_B =", sum(ABC_1$conv_B)/sum(ABC_1$n_B), "\n",
    
    "CR_C =", sum(ABC_1$conv_C)/sum(ABC_1$n_C), "\n")

head(ABC_1)

```


```{r Epsilon-Greedy}

###############################################################################
############################### Epsilon-Greedy Algorithm ######################

# PARAMETERS

set.seed(123)

pA <- 0.09; pB <- 0.15; pC <- 0.10

traffic <- 30000

rounds <- 100

ABC_2 <- data.table()

conv_Tot <- 0

traffic_tot <- 0

net_conv <- 0

epsilon <- 0.2

conv_A_tot <- 0
conv_B_tot <- 0
conv_C_tot <- 0

net_traffic_A <- 0
net_traffic_B <- 0
net_traffic_C <- 0

rate_round_A <- 0
rate_round_B <- 0
rate_round_C <- 0

# SIMULATION

for (round in 1:rounds) {
  
  if(round == 1){
    
    n_A=round(traffic/3,0)
    
    n_B=round(traffic/3,0)
    
    n_C=round(traffic/3,0)
    
  }
  else {
    
    rand_num <- runif(1, min = 0, max = 1)
    
    if(rand_num > epsilon){
      
      n_A = ifelse(rate_round_A > rate_round_B && rate_round_A > rate_round_C, traffic, 0)
      n_B = ifelse(rate_round_B > rate_round_A && rate_round_B > rate_round_C, traffic, 0)
      n_C = ifelse(rate_round_C > rate_round_A && rate_round_C > rate_round_B, traffic, 0)
    }
    else {
      
      random <- sample(1:3,1, replace = TRUE)
      
      n_A = ifelse(random == 1, traffic, 0)
      n_B = ifelse(random == 2, traffic, 0)
      n_C = ifelse(random == 3, traffic, 0)
    }
    
    
  }
  
  
  conv_A = ifelse(n_A == 0, 0, sum(rbinom(n_A, 1, pA)))
  conv_A_tot <- conv_A_tot + conv_A
  net_traffic_A <- net_traffic_A + n_A
  rate_round_A <- conv_A_tot/net_traffic_A
  
  conv_B = ifelse(n_B == 0, 0, sum(rbinom(n_B, 1, pB))) 
  conv_B_tot <- conv_B_tot + conv_B
  net_traffic_B <- net_traffic_B + n_B
  rate_round_B <- conv_B_tot/net_traffic_B
  
  conv_C = ifelse(n_C == 0, 0, sum(rbinom(n_C, 1, pC))) 
  conv_C_tot <- conv_C_tot + conv_C
  net_traffic_C <- net_traffic_C + n_C
  rate_round_C <- conv_C_tot/net_traffic_C
  
  conv_total = sum(conv_A,conv_B,conv_C)
  
  cr_A = ifelse(n_A == 0, 0, round(conv_A/(n_A),2))
  
  cr_B = ifelse(n_B == 0, 0, round(conv_B/(n_B),2))
  
  cr_C = ifelse(n_C == 0, 0, round(conv_C/(n_C),2))
  
  cr_total=round(conv_total/(n_A+n_B+n_C),2)
  
  conv_Tot <- conv_Tot + conv_total
  
  traffic_tot <- traffic_tot + n_A + n_B + n_C
  
  net_conv <- conv_Tot/traffic_tot
  
  ABC_2 <- rbind(ABC_2, data.table(round, traffic, n_A, n_B, n_C, conv_total, conv_A, conv_B, conv_C, cr_total, cr_A, cr_B, cr_C, conv_Tot, traffic_tot, net_conv))
  rate <- c(cr_A, cr_B, cr_C)
  
}

# OUTPUT RESULTS

cat("\nTotal Results for", rounds, "Rounds\n",
    
    "Visitors_Total =", sum(ABC_2$traffic), "\n",
    
    "Visitors_A =", sum(ABC_2$n_A), "\n",
    
    "Visitors_B =", sum(ABC_2$n_B), "\n",
    
    "Visitors_C =", sum(ABC_2$n_C), "\n",
    
    "Total Conversions =", sum(ABC_2$conv_total), "\n",
    
    "Conversions for A =", sum(ABC_2$conv_A), "\n",
    
    "Conversions for B =", sum(ABC_2$conv_B), "\n",
    
    "Conversions for C =", sum(ABC_2$conv_C), "\n",
    
    "CR Total=", sum(ABC_2$conv_total)/sum(ABC_2$traffic) * 100,"%", "\n",
    
    "CR_A =", sum(ABC_2$conv_A)/sum(ABC_2$n_A), "\n",
    
    "CR_B =", sum(ABC_2$conv_B)/sum(ABC_2$n_B), "\n",
    
    "CR_C =", sum(ABC_2$conv_C)/sum(ABC_2$n_C), "\n")

head(ABC_2)


```


```{r Softmax}

##################################################################################
############################# Soft max Algorithm ########################################


# PARAMETERS

set.seed(123)

pA <- 0.09; pB <- 0.15; pC <- 0.10

traffic <- 30000

rounds <- 100

ABC_3 <- data.table()

conv_Tot <- 0

traffic_tot <- 0

net_conv <- 0

tau <- 0.25

conv_A_tot <- 0
conv_B_tot <- 0
conv_C_tot <- 0

net_traffic_A <- 0
net_traffic_B <- 0
net_traffic_C <- 0

rate_round_A <- 0
rate_round_B <- 0
rate_round_C <- 0

# SIMULATION

for (round in 1:rounds) {
  
  if(round == 1){
    
    n_A=round(traffic/3,0)
    
    n_B=round(traffic/3,0)
    
    n_C=round(traffic/3,0)
    
  }
  else {
    
    p_A <- exp(rate_round_A/tau)/sum(exp(rate_round_A/tau)+exp(rate_round_B/tau)+exp(rate_round_C/tau))
    p_B <- exp(rate_round_B/tau)/sum(exp(rate_round_A/tau)+exp(rate_round_B/tau)+exp(rate_round_C/tau))
    p_C <- exp(rate_round_C/tau)/sum(exp(rate_round_A/tau)+exp(rate_round_B/tau)+exp(rate_round_C/tau))
    
    rand_num <- runif(1, min = 0, max = 1)
    
    if(p_A > rand_num){
      n_A = traffic
      n_B = 0
      n_C = 0
    }
    else if (p_A + p_B > rand_num){
      n_A = 0
      n_B = traffic
      n_C = 0
    }
    else {
      n_A = 0
      n_B = 0
      n_C = traffic
    }
    
  }
  
  
  conv_A = ifelse(n_A == 0, 0, sum(rbinom(n_A, 1, pA)))
  conv_A_tot <- conv_A_tot + conv_A
  net_traffic_A <- net_traffic_A + n_A
  rate_round_A <- conv_A_tot/net_traffic_A
  
  conv_B = ifelse(n_B == 0, 0, sum(rbinom(n_B, 1, pB))) 
  conv_B_tot <- conv_B_tot + conv_B
  net_traffic_B <- net_traffic_B + n_B
  rate_round_B <- conv_B_tot/net_traffic_B
  
  conv_C = ifelse(n_C == 0, 0, sum(rbinom(n_C, 1, pC))) 
  conv_C_tot <- conv_C_tot + conv_C
  net_traffic_C <- net_traffic_C + n_C
  rate_round_C <- conv_C_tot/net_traffic_C
  
  conv_total = sum(conv_A,conv_B,conv_C)
  
  cr_A = ifelse(n_A == 0, 0, round(conv_A/(n_A),2))
  
  cr_B = ifelse(n_B == 0, 0, round(conv_B/(n_B),2))
  
  cr_C = ifelse(n_C == 0, 0, round(conv_C/(n_C),2))
  
  cr_total=round(conv_total/(n_A+n_B+n_C),2)
  
  conv_Tot <- conv_Tot + conv_total
  
  traffic_tot <- traffic_tot + n_A + n_B + n_C
  
  net_conv <- conv_Tot/traffic_tot
  
  ABC_3 <- rbind(ABC_3, data.table(round, traffic, n_A, n_B, n_C, conv_total, conv_A, conv_B, conv_C, cr_total, cr_A, cr_B, cr_C, conv_Tot, traffic_tot, net_conv))
  rate <- c(cr_A, cr_B, cr_C)
  
}

# OUTPUT RESULTS

cat("\nTotal Results for", rounds, "Rounds\n",
    
    "Visitors_Total =", sum(ABC_3$traffic), "\n",
    
    "Visitors_A =", sum(ABC_3$n_A), "\n",
    
    "Visitors_B =", sum(ABC_3$n_B), "\n",
    
    "Visitors_C =", sum(ABC_3$n_C), "\n",
    
    "Total Conversions =", sum(ABC_3$conv_total), "\n",
    
    "Conversions for A =", sum(ABC_3$conv_A), "\n",
    
    "Conversions for B =", sum(ABC_3$conv_B), "\n",
    
    "Conversions for C =", sum(ABC_3$conv_C), "\n",
    
    "CR Total=", sum(ABC_3$conv_total)/sum(ABC_3$traffic) * 100,"%", "\n",
    
    "CR_A =", sum(ABC_3$conv_A)/sum(ABC_3$n_A), "\n",
    
    "CR_B =", sum(ABC_3$conv_B)/sum(ABC_3$n_B), "\n",
    
    "CR_C =", sum(ABC_3$conv_C)/sum(ABC_3$n_C), "\n")

head(ABC_3)


```


```{r UCB}

#########################################################################################
############################### UCB Algorithm #############################################

# PARAMETERS

set.seed(123)

pA <- 0.09; pB <- 0.15; pC <- 0.10

traffic <- 30000

rounds <- 100

ABC_4 <- data.table()

conv_Tot <- 0

traffic_tot <- 0

net_conv <- 0


conv_A_tot <- 0
conv_B_tot <- 0
conv_C_tot <- 0

net_traffic_A <- 0
net_traffic_B <- 0
net_traffic_C <- 0

rate_round_A <- 0
rate_round_B <- 0
rate_round_C <- 0

# SIMULATION

for (round in 1:rounds) {
  
  if(round == 1){
    
    n_A <- round(traffic/3,0)
    count_A <- 1
    
    n_B <- round(traffic/3,0)
    count_B <- 1
    
    n_C <- round(traffic/3,0)
    count_C <- 1
    
  }
  else {
    
    UCB_A <- rate_round_A + sqrt(2*log(round)/count_A)
    UCB_B <- rate_round_B + sqrt(2*log(round)/count_B)
    UCB_C <- rate_round_C + sqrt(2*log(round)/count_C)
    
    if(UCB_A > UCB_B && UCB_A > UCB_C){
      n_A = traffic
      n_B = 0
      n_C = 0
      count_A <- count_A + 1
    }
    else if (UCB_B > UCB_A && UCB_B > UCB_C){
      n_A = 0
      n_B = traffic
      n_C = 0
      count_B <- count_B + 1
    }
    else {
      n_A = 0
      n_B = 0
      n_C = traffic
      count_C <- count_C + 1
    }
    
  }
  
  
  conv_A = ifelse(n_A == 0, 0, sum(rbinom(n_A, 1, pA)))
  conv_A_tot <- conv_A_tot + conv_A
  net_traffic_A <- net_traffic_A + n_A
  rate_round_A <- conv_A_tot/net_traffic_A
  
  conv_B = ifelse(n_B == 0, 0, sum(rbinom(n_B, 1, pB))) 
  conv_B_tot <- conv_B_tot + conv_B
  net_traffic_B <- net_traffic_B + n_B
  rate_round_B <- conv_B_tot/net_traffic_B
  
  conv_C = ifelse(n_C == 0, 0, sum(rbinom(n_C, 1, pC))) 
  conv_C_tot <- conv_C_tot + conv_C
  net_traffic_C <- net_traffic_C + n_C
  rate_round_C <- conv_C_tot/net_traffic_C
  
  conv_total = sum(conv_A,conv_B,conv_C)
  
  cr_A = ifelse(n_A == 0, 0, round(conv_A/(n_A),2))
  
  cr_B = ifelse(n_B == 0, 0, round(conv_B/(n_B),2))
  
  cr_C = ifelse(n_C == 0, 0, round(conv_C/(n_C),2))
  
  cr_total=round(conv_total/(n_A+n_B+n_C),2)
  
  conv_Tot <- conv_Tot + conv_total
  
  traffic_tot <- traffic_tot + n_A + n_B + n_C
  
  net_conv <- conv_Tot/traffic_tot
  
  ABC_4 <- rbind(ABC_4, data.table(round, traffic, n_A, n_B, n_C, conv_total, conv_A, conv_B, conv_C, cr_total, cr_A, cr_B, cr_C, conv_Tot, traffic_tot, net_conv, count_A, count_B, count_C))
 
  
}

# OUTPUT RESULTS

cat("\nTotal Results for", rounds, "Rounds\n",
    
    "Visitors_Total =", sum(ABC_4$traffic), "\n",
    
    "Visitors_A =", sum(ABC_4$n_A), "\n",
    
    "Visitors_B =", sum(ABC_4$n_B), "\n",
    
    "Visitors_C =", sum(ABC_4$n_C), "\n",
    
    "Total Conversions =", sum(ABC_4$conv_total), "\n",
    
    "Conversions for A =", sum(ABC_4$conv_A), "\n",
    
    "Conversions for B =", sum(ABC_4$conv_B), "\n",
    
    "Conversions for C =", sum(ABC_4$conv_C), "\n",
    
    "CR Total=", sum(ABC_4$conv_total)/sum(ABC_4$traffic) * 100,"%", "\n",
    
    "CR_A =", sum(ABC_4$conv_A)/sum(ABC_4$n_A), "\n",
    
    "CR_B =", sum(ABC_4$conv_B)/sum(ABC_4$n_B), "\n",
    
    "CR_C =", sum(ABC_4$conv_C)/sum(ABC_4$n_C), "\n")

head(ABC_4)

```